### PR TITLE
Using Kestrel with paket 2.61

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
works

**Comment by CumpsD** [comment]
Thanks :)

**Comment by forki** [comment]
Still open question on how to handle the native runtime dll

**Comment by CumpsD** [comment]
The libuv.dll? True, no idea really, even with regular nuget I found a post somewhere which advised to manually reference it for now, I guess they havent solved it yet themselves

**Comment by forki** [comment]
I have an idea. Will try tomorrow

**Comment by davidfowl** [comment]
@forki ping me about the implementation 😄

**Pull request merged**
